# 文件命名规则 --> Application & profile -> {application}-{profile}.yml(.properties、.json)
info:
  profile: prod
  
name: config-consumer-prod
words: 'hello welcome to config  to prod -------- and refresh '
